# ch·∫°y zookeeper tr∆∞·ªõc


services:
#  You‚Äôre using INTERNAL://kafka-broker-01:19092 between containers, so we connect UI using 19092, not 9092.
#  docker-compose -f kafka-deployment.yaml up -d kafka-ui
#   Then open:
#
#  üëâ http://localhost:8085
#
#  You should see the Kafka UI dashboard with your cluster local.
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-01:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-01:2181
    networks:
      - shopapp-network
    depends_on:
      - kafka-broker-01


  zookeeper-01:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper-01
    container_name: zookeeper-01
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      #ƒê·ªãnh nghƒ©a danh s√°ch c√°c m√°y ch·ªß Zookeeper trong cluster, bao g·ªìm ch√≠nh zookeeper-01 v√† hai m√°y ch·ªß kh√°c zookeeper-02 v√† zookeeper-03
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
      #2888: Port ƒë∆∞·ª£c s·ª≠ d·ª•ng cho giao ti·∫øp gi·ªØa c√°c m√°y ch·ªß Zookeeper
      #3888: Port ƒë∆∞·ª£c s·ª≠ d·ª•ng cho giao ti·∫øp gi·ªØa c√°c client v√† m√°y ch·ªß Zookeeper.

    networks:
      - shopapp-network
    # volumes:
    #   - zookeeper-01-data:/var/lib/zookeeper

  zookeeper-02:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper-02
    container_name: zookeeper-02
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
    networks:
      - shopapp-network
    # volumes:
    #   - zookeeper-02-data:/var/lib/zookeeper

  zookeeper-03:
    image: confluentinc/cp-zookeeper:7.5.3
    hostname: zookeeper-03
    container_name: zookeeper-03
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper-01:2888:3888;zookeeper-02:2888:3888;zookeeper-03:2888:3888
    networks:
      - shopapp-network  
    # volumes:
    #   - zookeeper-03-data:/var/lib/zookeeper


  kafka-broker-01:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka-broker-01
    container_name: kafka-broker-01
    ports:
      - "9092:9092" #Cho ph√©p truy c·∫≠p giao ti·∫øp client v·ªõi Kafka qua port 9092 tr√™n m√°y ch·ªß
      - "29092:29092" #Cho ph√©p giao ti·∫øp gi·ªØa c√°c broker Kafka trong cluster
      - "9999:9999" #Cho ph√©p truy c·∫≠p JMX (Java Management Extensions) c·ªßa Kafka qua port 9999 tr√™n m√°y ch·ªß
    environment:
      #ƒê·ªãnh nghƒ©a c√°c listener c·ªßa Kafka v√† ƒë·ªãa ch·ªâ truy c·∫≠p
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-01:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      #INTERNAL://kafka-broker-01:19092: Listener n·ªôi b·ªô cho giao ti·∫øp gi·ªØa c√°c container Kafka
      #EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092: Listener b√™n ngo√†i cho ph√©p client b√™n ngo√†i truy c·∫≠p Kafka th√¥ng qua port 9092 tr√™n m√°y ch·ªß
      #DOCKER://host.docker.internal:29092: Listener cho ph√©p giao ti·∫øp gi·ªØa c√°c container Kafka trong cluster docker

      #Thi·∫øt l·∫≠p giao th·ª©c b·∫£o m·∫≠t cho t·ª´ng listener, trong tr∆∞·ªùng h·ª£p n√†y t·∫•t c·∫£ ƒë·ªÅu d√πng PLAINTEXT (kh√¥ng m√£ h√≥a).
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT      

      #X√°c ƒë·ªãnh listener d√πng cho giao ti·∫øp gi·ªØa c√°c broker Kafka, trong tr∆∞·ªùng h·ª£p n√†y l√† INTERNAL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-01:2181,zookeeper-02:2182,zookeeper-03:2183"
      KAFKA_BROKER_ID: 1

      #C·∫•u h√¨nh m·ª©c ƒë·ªô log cho c√°c th√†nh ph·∫ßn c·ªßa Kafka
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

      #Thi·∫øt l·∫≠p s·ªë b·∫£n sao cho ch·ªß ƒë·ªÅ offset trong Kafka
      #topic "offset" l∆∞u th√¥ng tin v·ªÅ v·ªã tr√≠ ƒë·ªçc cu·ªëi c√πng c·ªßa m·ªói consumer trong m·ªói ph√¢n v√πng c·ªßa 1 Kafka topic
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      #s·ªë b·∫£n sao cho ch·ªß ƒë·ªÅ nh·∫≠t k√Ω tr·∫°ng th√°i giao d·ªãch (transaction state log) trong Kafka
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #Ch·ªß ƒë·ªÅ n√†y l∆∞u tr·ªØ th√¥ng tin v·ªÅ tr·∫°ng th√°i c·ªßa c√°c giao d·ªãch
      #cho ph√©p Kafka kh√¥i ph·ª•c giao d·ªãch dang d·ªü trong tr∆∞·ªùng h·ª£p broker g·∫∑p s·ª± c·ªë.

      #Thi·∫øt l·∫≠p s·ªë l∆∞·ª£ng broker t·ªëi thi·ªÉu ph·∫£i x√°c nh·∫≠n m·ªôt b·∫£n ghi m·ªõi trong nh·∫≠t k√Ω 
      #tr·∫°ng th√°i giao d·ªãch tr∆∞·ªõc khi ƒë∆∞·ª£c coi l√† ho√†n th√†nh
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      #Gi√° tr·ªã n√†y ƒë·∫£m b·∫£o r·∫±ng d·ªØ li·ªáu giao d·ªãch ƒë∆∞·ª£c l∆∞u tr·ªØ tr√™n ƒë·ªß s·ªë broker

      #Thi·∫øt l·∫≠p port v√† hostname cho JMX c·ªßa Kafka
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer

      #Cho ph√©p m·ªçi ng∆∞·ªùi truy c·∫≠p n·∫øu kh√¥ng c√≥ ACL n√†o ƒë∆∞·ª£c t√¨m th·∫•y
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    
    networks:
      - shopapp-network
    # volumes:
    #   - kafka-broker-01-data:/var/lib/kafka/data
    depends_on:
      - zookeeper-01
      - zookeeper-02
      - zookeeper-03
    restart: always



  kafka-broker-02:
     image: confluentinc/cp-kafka:7.5.3
     hostname: kafka-broker-02
     container_name: kafka-broker-02
     ports:
       - "9093:9093"
       - "29093:29093"
     environment:
       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-02:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
       KAFKA_ZOOKEEPER_CONNECT: "zookeeper-01:2181,zookeeper-02:2182,zookeeper-03:2183"
       KAFKA_BROKER_ID: 2
       KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
       KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
       KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
          
     depends_on:
       - zookeeper-01
       - zookeeper-02
       - zookeeper-03
#     volumes:
#       - kafka-broker-02-data:/var/lib/kafka/data


networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge

volumes:
  zookeeper-01-data:
  zookeeper-02-data:
  zookeeper-03-data:
  kafka-broker-01-data:
  kafka-broker-02-data:

#docker rm -f zookeeper-01 zookeeper-02 zookeeper-03 kafka-broker-01

#docker-compose -f ./kafka-deployment.yaml up -d zookeeper-01
#docker-compose -f ./kafka-deployment.yaml up -d zookeeper-02
#docker-compose -f ./kafka-deployment.yaml up -d zookeeper-03

#docker-compose -f ./kafka-deployment.yaml up -d kafka-broker-01
#docker-compose -f ./kafka-deployment.yaml up -d kafka-broker-02


